# Generated by Django 3.2.8 on 2021-10-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentValue1', models.IntegerField(default=0, null=True)),
                ('currentValue2', models.IntegerField(default=0, null=True)),
                ('currentValue3', models.IntegerField(default=0, null=True)),
                ('currentValue4', models.IntegerField(default=0, null=True)),
                ('currentValue5', models.IntegerField(default=0, null=True)),
                ('currentValue6', models.IntegerField(default=0, null=True)),
                ('currentValue7', models.IntegerField(default=0, null=True)),
                ('futureValue1', models.IntegerField(default=0, null=True)),
                ('futureValue2', models.IntegerField(default=0, null=True)),
                ('futureValue3', models.IntegerField(default=0, null=True)),
                ('futureValue4', models.IntegerField(default=0, null=True)),
                ('futureValue5', models.IntegerField(default=0, null=True)),
                ('futureValue6', models.IntegerField(default=0, null=True)),
                ('futureValue7', models.IntegerField(default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
