# Generated by Django 3.2.8 on 2021-10-31 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=40, null=True)),
                ('account_img', models.ImageField(default='img/no_image.png', null=True, upload_to='img/')),
                ('description', models.CharField(default='-', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(default='입금', max_length=10, null=True)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deposit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.account')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
