# Generated by Django 3.2.8 on 2021-10-31 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_account_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amount', models.IntegerField(default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.account')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
