# Generated by Django 3.2.8 on 2021-10-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
