# Generated by Django 3.2.8 on 2021-10-31 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211031_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_account',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='home.account'),
        ),
    ]
