# Generated by Django 3.2.8 on 2021-10-31 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_deposit_deposit_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_account',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='home.account'),
        ),
    ]
