# Generated by Django 3.2.8 on 2021-10-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_deposit_deposit_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='created',
            field=models.DateField(null=True),
        ),
    ]
