# Generated by Django 3.2.8 on 2021-10-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_asset_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
