# Generated by Django 3.2.8 on 2021-10-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_asset_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['ordering_level']},
        ),
        migrations.AddField(
            model_name='account',
            name='ordering_level',
            field=models.IntegerField(null=True),
        ),
    ]
