# Generated by Django 3.2.8 on 2021-11-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_deposit_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
